[build-system]
name = "ebook2audiobook"
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "ebook2audiobook"
version = "0.0.0"

[tool.setuptools.dynamic]
version = {file = "VERSION.txt"}

[project]
name = "ebook2audiobook"
description = "Convert eBooks to audiobooks with chapters and metadata"
authors = [
    { name = "Drew Thomasson" }
]
dependencies = [
	"beautifulsoup4",
	"cutlet",
	"deep_translator",
	"demucs",
	"docker",
	"ebooklib",
	"fastapi",
	"ffmpeg-python",
	"gensim",
	"gradio",
	"hangul-romanize",
	"indic-nlp-library",
	"iso-639",
	"jieba",
	"m4b-util",
	"mecab",
	"mecab-python3",
	"pydub",
	"nvidia-ml-py",
	"PyOpenGL",
	"pypinyin",
	"ray",
	"regex",
	"sentencepiece",
	"transformers",
	"translate",
	"tqdm",
	"unidic",
	"torchvggish",
	"pymupdf4llm",
	"torch==2.4.1",
	"torchaudio==2.4.1",
	"torchvision==0.19.1",
	"coqui-tts==0.25.3"
]
readme = "README.md"
requires-python = ">3.11,<3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
scripts = { "ebook2audiobook" = "app:main" }

[project.urls]
"Homepage" = "https://github.com/DrewThomasson/ebook2audiobook"