name: Lite Self-Hosted

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Command on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Running on Windows..."
          ./ebook2audiobook.cmd --help
          conda env list

      - name: Run Command on Mac/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Running on Mac/Linux..."
          chmod +x ./ebook2audiobook.sh
          ./ebook2audiobook.sh --help
          conda env list

      - name: Activate Conda environment on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Activating Conda environment on Windows..."
          call conda activate /Users/drew/actions-runner/_work/ebook2audiobook/ebook2audiobook/python_env
          python --version  # Check if environment is activated

      - name: Activate Conda environment on Mac/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Activating Conda environment on Mac/Linux..."
          # Initialize conda with the correct path
          source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh
          
          # Activate your environment
          conda activate /Users/drew/actions-runner/_work/ebook2audiobook/ebook2audiobook/python_env
          
          # Verify activation
          python --version

          #Download unidict
          python -c "import unidic; unidic.download()"

      - name: pip install requirements.txt Mac/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Activating Conda environment on Mac/Linux..."
          # Initialize conda with the correct path
          source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh
          
          # Activate your environment
          conda activate /Users/drew/actions-runner/_work/ebook2audiobook/ebook2audiobook/python_env

          pip install -r requirements.txt


      - name: app.py --help Mac/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Activating Conda environment on Mac/Linux..."
          # Initialize conda with the correct path
          source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh
          
          # Activate your environment
          conda activate /Users/drew/actions-runner/_work/ebook2audiobook/ebook2audiobook/python_env

          python app.py --help

      - name: app.py vits run Mac/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Activating Conda environment on Mac/Linux..."
          # Initialize conda with the correct path
          source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh
          
          # Activate your environment
          conda activate /Users/drew/actions-runner/_work/ebook2audiobook/ebook2audiobook/python_env

          python app.py --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine vits
