name: Lite Self-Hosted

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Command on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Running on Windows..."
          ./ebook2audiobook.cmd --help
          conda env list

      - name: Run Command on Mac/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Running on Mac/Linux..."
          chmod +x ./ebook2audiobook.sh
          ./ebook2audiobook.sh --help
          conda env list
