name: Lite Self-Hosted

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Command on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Running on Windows..."
          ./ebook2audiobook.cmd --help
          conda env list

      - name: Run Command on Mac/Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Running on Mac/Linux..."
          chmod +x ./ebook2audiobook.sh
          ./ebook2audiobook.sh --help
          conda env list

      - name: Activate conda environment on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Activating Conda environment on Windows..."
          call conda activate /Users/drew/actions-runner/_work/ebook2audiobook/ebook2audiobook/python_env
          python --version  # Check if environment is activated

      - name: Activate conda environment on Mac/Linux
        if: runner.os != 'Windows'
        shell: bash -l  # Use login shell to ensure conda is available
        run: |
          echo "Activating Conda environment on Mac/Linux..."
          source ~/miniconda3/etc/profile.d/conda.sh  # Ensure conda is initialized
          conda activate /Users/drew/actions-runner/_work/ebook2audiobook/ebook2audiobook/python_env
          python --version  # Check if environment is activated
