name: full Test Ubuntu Headless

on:
  push:
    branches:
      - act-trigger
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  run-script:
    runs-on: [self-hosted]  # [self-hosted, ubuntu-latest] Attempts self-hosted first, then falls back to ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: A docker test that is suppose to succeed
        run: docker run athomasson2/ebook2audiobook:latest --help

      - name: A docker run test that is suppose to fail
        run: docker run athomasson2/ebook2audiobook:latest --sldfjosdosdisdfoisdofijsd OOOGAH BOOGEH 

      - name: Create test files
        run: |
          mkdir -p workflow-testing
          CONTENT=$'"This is a test sentence," she said. "Here'\''s another one."\nThe quick brown fox jumps over the lazy dog, but the cat stays still.\nNumbers like 123,456.78 should also be tested.\nWhat happens if we use question marks? Or exclamation points!\n"Nested quotes are '\''interesting'\''," he noted.'
          echo -e "$CONTENT" > workflow-testing/test1.txt
          echo -e "$CONTENT" > workflow-testing/test2.txt
          echo -e "$CONTENT" > workflow-testing/test3.txt
          echo -e "$CONTENT" > workflow-testing/test4.txt
          echo -e "$CONTENT" > workflow-testing/test5.txt

      - name: move test script to main dir
        run: mv tools/headlessDockerTester.sh headlessDockerTester.sh

      - name: Grant execution permission to script
        run: chmod +x headlessDockerTester.sh

      - name: English Fairseq headless single test python app.py
        run: ./headlessDockerTester.sh --headless --script_mode full_docker --language eng --ebook "workflow-testing/test1.txt" --tts_engine fairseq

      - name: English Fairseq headless batch test python app.py
        run: ./headlessDockerTester.sh --headless --script_mode full_docker --language eng --ebooks_dir "workflow-testing" --tts_engine fairseq

      - name: list out all the docker images
        run: docker image list

      - name: Remove any dangling images (ones without any tags)
        run: docker image prune -f

      - name: list out all the docker images
        run: docker image list

      - name: (Suppose to fail) English Fairseq headless single test python app.py
        run: ./headlessDockerTester.sh --headless --script_mode full_docker --language eng --ebook "workflow-testing/testdsddfs1.txtt" --tts_engine fairseq
