name: full Test Ubuntu Headless

on:
  push:
    branches:
      - act-trigger
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create fail script
        run: echo -e "#!/bin/bash\nexit 1" > fail.sh
      
      - name: Make script executable
        run: chmod +x fail.sh
      
      - name: Run fail script
        run: ./fail.sh
