name: full Test Ubuntu Headless

on:
  push:
    branches:
      - act-trigger
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  run-script:
    runs-on: [ubuntu-latest]  # [self-hosted, ubuntu-latest] Attempts self-hosted first, then falls back to ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create test files
        run: |
          mkdir -p workflow-testing
          CONTENT=$'"This is a test sentence," she said. "Here'\''s another one."\nThe quick brown fox jumps over the lazy dog, but the cat stays still.\nNumbers like 123,456.78 should also be tested.\nWhat happens if we use question marks? Or exclamation points!\n"Nested quotes are '\''interesting'\''," he noted.'
          echo -e "$CONTENT" > workflow-testing/test1.txt
          echo -e "$CONTENT" > workflow-testing/test2.txt
          echo -e "$CONTENT" > workflow-testing/test3.txt
          echo -e "$CONTENT" > workflow-testing/test4.txt
          echo -e "$CONTENT" > workflow-testing/test5.txt

      - name: move test script to main dir
        run: mv tools/headlessDockerTester.sh headlessDockerTester.sh

      - name: Grant execution permission to script
        run: chmod +x headlessDockerTester.sh

      - name: English Fairseq headless single test python app.py
        run: ./headlessDockerTester.sh --headless --script_mode full_docker --language eng --ebook "workflow-testing/test1.txt" --tts_engine fairseq
