name: lite Ubuntu Headless

on:
  workflow_dispatch:
    inputs:
      tts_engine:
        description: 'TTS Engine to use'
        required: true
        default: 'xtts'
        type: choice
        options:
          - fairseq
          - vits
          - yourtts
          - xtts
      mode:
        description: 'Processing mode'
        required: true
        default: 'single'
        type: choice
        options:
          - single
          - batch
      use_custom_voice:
        description: 'Use custom voice'
        required: true
        default: 'false'
        type: boolean
      language:
        description: 'Language code'
        required: true
        default: 'eng'
        type: string

jobs:
  run-tts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y gcc g++ make wget git calibre ffmpeg nodejs espeak espeak-ng rustc cargo libmecab-dev mecab mecab-ipadic-utf8 curl libsndfile1-dev libc-dev sox &&
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash - &&
          sudo apt-get install -y nodejs &&
          sudo apt-get clean &&
          sudo rm -rf /var/lib/apt/lists/*

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          pip install -r requirements.txt

      - name: Install unict
        run: pip install unidic-lite unidic

      - name: Download unict dictionary
        run: |
          python -m unidic download
          mkdir -p ~/.local/share/unidic

      - name: Set UniDic environment variable
        run: echo "UNIDIC_DIR=$HOME/.local/share/unidic" >> $GITHUB_ENV

      - name: Run Single Mode with Default Voice
        if: ${{ inputs.mode == 'single' && inputs.use_custom_voice == 'false' }}
        run: python app.py --headless --script_mode full_docker --language ${{ inputs.language }} --ebook "tools/workflow-testing/test1.txt" --tts_engine ${{ inputs.tts_engine }}

      - name: Run Batch Mode with Default Voice
        if: ${{ inputs.mode == 'batch' && inputs.use_custom_voice == 'false' }}
        run: python app.py --headless --script_mode full_docker --language ${{ inputs.language }} --ebooks_dir "tools/workflow-testing" --tts_engine ${{ inputs.tts_engine }}

      - name: Run Single Mode with Custom Voice
        if: ${{ inputs.mode == 'single' && inputs.use_custom_voice == 'true' }}
        run: python app.py --headless --script_mode full_docker --language ${{ inputs.language }} --ebook "tools/workflow-testing/test1.txt" --tts_engine ${{ inputs.tts_engine }} --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: Run Batch Mode with Custom Voice
        if: ${{ inputs.mode == 'batch' && inputs.use_custom_voice == 'true' }}
        run: python app.py --headless --script_mode full_docker --language ${{ inputs.language }} --ebooks_dir "tools/workflow-testing" --tts_engine ${{ inputs.tts_engine }} --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: Upload audiobooks as artifact
        uses: actions/upload-artifact@v4
        with:
          name: audiobooks
          path: audiobooks/
          retention-days: 3
