name: Run Docker and Upload Audiobooks

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag to use"
        required: true
        default: "latest"

jobs:
  run-and-upload:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Create output directory in shared location
        run: |
          mkdir -p /tmp/audiobooks
          chmod 777 -R /tmp/audiobooks

      - name: Run Docker container with bind mount
        run: |
          # Check if OUTDIR environment variable is supported
          docker run --rm \
            -v /tmp:/tmp \
            -e OUTDIR="/tmp/audiobooks" \
            ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ github.event.inputs.docker_tag }} \
            --headless --script_mode full_docker \
            --language eng \
            --ebook "tools/workflow-testing/test1.txt" \
            --tts_engine fairseq

      - name: Search for generated audiobook files
        run: |
          echo "=== Searching for generated audiobook files ==="
          find /tmp -name "*.m4b" -o -name "*.mp3" | tee /tmp/found_files.txt
          
          if [ -s /tmp/found_files.txt ]; then
            echo "✅ Found audiobook files"
            mkdir -p /tmp/collected_audiobooks
            
            while IFS= read -r file; do
              echo "Copying $file to collection directory"
              cp "$file" /tmp/collected_audiobooks/
            done < /tmp/found_files.txt
          else
            echo "❌ No audiobook files found!"
            echo "DEBUG: Contents of /tmp directory:"
            find /tmp -type f -name "*.txt" -o -name "*.flac" -o -name "*.wav"
            exit 1
          fi

      - name: Create ZIP archive and upload
        run: |
          cd /tmp
          echo "=== Creating ZIP archive ==="
          zip -r audiobooks.zip collected_audiobooks
          
          echo "=== ZIP contents ==="
          unzip -l audiobooks.zip
          
          if [[ -s "audiobooks.zip" ]]; then
            echo "=== Uploading audiobooks.zip ==="
            UPLOAD_URL=$(curl -F "file=@audiobooks.zip" https://0x0.st)
            echo "✅ Upload complete! File available at: $UPLOAD_URL"
          else
            echo "❌ ZIP archive is empty!"
            exit 1
          fi
