name: Run Docker and Upload Audiobooks
on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag to use"
        required: true
        default: "latest"
jobs:
  run-and-upload:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Run Docker container with self-contained process
        run: |
          docker run --rm \
            ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ github.event.inputs.docker_tag }} \
            bash -c '
              # Step 1: Run the conversion
              ./run_script.sh --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine fairseq && \
              
              # Step 2: Find all generated audiobooks and create zip
              OUTDIR=${OUTDIR:-/app/output}
              cd $OUTDIR && \
              
              # Step 3: Create zip file
              mkdir -p /tmp/audiobooks_to_upload
              find . -name "*.m4b" -o -name "*.mp3" -exec cp {} /tmp/audiobooks_to_upload \; && \
              cd /tmp && \
              zip -r audiobooks.zip audiobooks_to_upload && \
              
              # Step 4: Upload to file sharing service
              UPLOAD_URL=$(curl -F "file=@audiobooks.zip" https://0x0.st) && \
              echo "✅ UPLOAD_URL: $UPLOAD_URL"
            '
