name: lite test
on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag to use for testing'
        required: false
        default: 'lite_dev_v25'
        type: string
      tts_engine:
        description: 'TTS Engine to use'
        required: false
        default: 'fairseq'
        type: choice
        options:
          - all
          - fairseq
          - vits
          - yourtts
          - xtts
          - bark
      mode:
        description: 'Processing mode'
        required: false
        default: 'single'
        type: choice
        options:
          - all
          - single
          - batch
      use_custom_voice:
        description: 'Use custom voice'
        required: false
        default: 'false'
        type: choice
        options:
          - all
          - true
          - false
      language:
        description: 'Language code'
        required: false
        default: 'eng'
        type: string
      run_help_test:
        description: 'Run help command test'
        required: false
        default: 'true'
        type: boolean

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    env:
      DOCKER_TAG: ${{ inputs.docker_tag || 'lite_dev_v25' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx conditionally based on OS
      - name: Set up Docker Buildx (Windows)
        if: runner.os == 'Windows'
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx (Unix)
        if: runner.os != 'Windows'
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get Git Commit Hash
      - name: Get Git Commit Hash
        id: git_hash
        run: echo "GIT_HASH=$(git rev-parse --short=9 HEAD)" >> $GITHUB_ENV
        shell: bash

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/arm64 \
            --build-arg SKIP_XTTS_TEST=true \
            -t ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ env.DOCKER_TAG }} \
            --push .
        shell: bash

  generate_test_matrix:
    needs: build
    runs-on: [self-hosted, Linux, ARM64]
    outputs:
      test_matrix: ${{ steps.set_matrix.outputs.test_matrix }}
      help_test: ${{ steps.set_matrix.outputs.help_test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Generate test matrix
        id: set_matrix
        run: |
          # Define parameters for the test matrix
          ENGINES=("fairseq" "vits" "yourtts" "xtts" "bark")
          MODES=("single" "batch")
          VOICES=("default" "custom")
          LANGS=("${{ inputs.language }}")
          
          # If "all" is specified for language, use the predefined list of languages
          if [[ "${{ inputs.language }}" == "all" ]]; then
            LANGS=("eng" "urd-script_devanagari")
          fi
          
          # Filter based on input parameters
          if [[ "${{ inputs.tts_engine }}" != "all" ]]; then
            ENGINES=("${{ inputs.tts_engine }}")
          fi
          
          if [[ "${{ inputs.mode }}" != "all" ]]; then
            MODES=("${{ inputs.mode }}")
          fi
          
          if [[ "${{ inputs.use_custom_voice }}" != "all" ]]; then
            if [[ "${{ inputs.use_custom_voice }}" == "true" ]]; then
              VOICES=("custom")
            else
              VOICES=("default")
            fi
          fi
          
          # Initialize JSON array for test matrix
          echo "test_matrix=[" > matrix.json
          
          # Generate regular tests
          for ENGINE in "${ENGINES[@]}"; do
            for MODE in "${MODES[@]}"; do
              for VOICE in "${VOICES[@]}"; do
                for LANG in "${LANGS[@]}"; do
                  NAME="${LANG} ${ENGINE} headless"
                  if [[ "$VOICE" == "custom" ]]; then
                    NAME="${NAME} Custom-Voice"
                  fi
                  NAME="${NAME} ${MODE} test"
                  
                  CMD="--headless --script_mode full_docker --language ${LANG}"
                  
                  if [[ "$MODE" == "single" ]]; then
                    CMD="${CMD} --ebook \"tools/workflow-testing/test1.txt\""
                  else
                    CMD="${CMD} --ebooks_dir \"tools/workflow-testing\""
                  fi
                  
                  CMD="${CMD} --tts_engine ${ENGINE}"
                  
                  if [[ "$VOICE" == "custom" ]]; then
                    CMD="${CMD} --voice \"voices/eng/elder/male/DavidAttenborough_24000.wav\""
                  fi
                  
                  # Add to JSON array
                  echo "  {\"name\": \"${NAME}\", \"cmd\": \"${CMD}\"}," >> matrix.json
                done
              done
            done
          done
          
          # Add special XTTS fine-tuned tests if XTTS is included
          if [[ "${{ inputs.tts_engine }}" == "all" || "${{ inputs.tts_engine }}" == "xtts" ]]; then
            if [[ "${{ inputs.mode }}" == "all" || "${{ inputs.mode }}" == "single" ]]; then
              # Only run these tests for eng language
              if [[ "${{ inputs.language }}" == "all" || "${{ inputs.language }}" == "eng" ]]; then
                NAME="English XTTS headless fine-tuned XTTS model single test"
                CMD="--headless --script_mode full_docker --language eng --ebook \"tools/workflow-testing/test1.txt\" --tts_engine xtts --fine_tuned AiExplained"
                echo "  {\"name\": \"${NAME}\", \"cmd\": \"${CMD}\"}," >> matrix.json
              fi
            fi
            
            if [[ "${{ inputs.mode }}" == "all" || "${{ inputs.mode }}" == "batch" ]]; then
              # Only run these tests for eng language
              if [[ "${{ inputs.language }}" == "all" || "${{ inputs.language }}" == "eng" ]]; then
                NAME="English XTTS headless fine-tuned XTTS model batch test"
                CMD="--headless --script_mode full_docker --language eng --ebooks_dir \"tools/workflow-testing\" --tts_engine xtts --fine_tuned AiExplained"
                echo "  {\"name\": \"${NAME}\", \"cmd\": \"${CMD}\"}," >> matrix.json
              fi
            fi
          fi
          
          # Remove trailing comma if any tests were added
          sed -i '$ s/,$//' matrix.json
          
          # Close JSON array
          echo "]" >> matrix.json
          
          # Set output for test matrix
          echo "test_matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT
          
          # Set output for help test
          if [[ "${{ inputs.run_help_test }}" == "true" ]]; then
            echo "help_test=true" >> $GITHUB_OUTPUT
          else
            echo "help_test=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

  run_help_test:
    needs: generate_test_matrix
    if: needs.generate_test_matrix.outputs.help_test == 'true'
    runs-on: [self-hosted, Linux, ARM64]
    env:
      DOCKER_TAG: ${{ inputs.docker_tag || 'lite_dev_v25' }}
    steps:
      - name: Prune dangling Docker images
        run: docker image prune -f
        
      - name: Run help command test
        run: |
          echo "Running help command test"
          set +e
          docker run --rm --pull=always --gpus all ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ env.DOCKER_TAG }} --help
          STATUS=$?
          set -e
          
          if [ $STATUS -ne 0 ]; then
            echo "GPU run failed, trying without GPU support..."
            docker run --rm --pull=always ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ env.DOCKER_TAG }} --help
          fi
        shell: bash

  run_tests:
    needs: generate_test_matrix
    runs-on: [self-hosted, Linux, ARM64]
    strategy:
      fail-fast: false
      matrix: 
        test: ${{ fromJson(needs.generate_test_matrix.outputs.test_matrix) }}
    env:
      DOCKER_TAG: ${{ inputs.docker_tag || 'lite_dev_v25' }}
    steps:
      - name: Prune dangling Docker images
        run: docker image prune -f
      
      - name: Run ${{ matrix.test.name }}
        run: |
          echo "Running test: ${{ matrix.test.name }}"
          echo "Command: ${{ matrix.test.cmd }}"
          
          # First try with GPU
          set +e
          docker run --rm --pull=always --gpus all ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ env.DOCKER_TAG }} ${{ matrix.test.cmd }}
          STATUS=$?
          set -e
          
          # If GPU run failed, try without GPU
          if [ $STATUS -ne 0 ]; then
            echo "GPU run failed, trying without GPU support..."
            docker run --rm --pull=always ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ env.DOCKER_TAG }} ${{ matrix.test.cmd }}
          fi
        shell: bash
