name: Run Docker and Upload Audiobooks

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag to use"
        required: true
        default: "latest"

jobs:
  run-and-upload:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Create output directory and set permissions
        run: |
          mkdir -p /tmp/audiobooks/cli
          chmod 777 -R /tmp/audiobooks

      - name: Run Docker container with volume mount
        run: |
          docker run --rm \
            -v /tmp/audiobooks:/app/audiobooks \
            ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ github.event.inputs.docker_tag }} \
            --headless --script_mode full_docker \
            --language eng \
            --ebook "tools/workflow-testing/test1.txt" \
            --tts_engine fairseq

      - name: Check if files were copied
        run: |
          if [ -d /tmp/audiobooks ] && [ "$(ls -A /tmp/audiobooks)" ]; then
            echo "Files copied successfully:"
            ls -l /tmp/audiobooks
          else
            echo "No files found in /tmp/audiobooks!"
            exit 1
          fi

      - name: Inspect, zip & upload audiobooks folder
        shell: bash
        run: |
          echo "=== DIRECTORY STRUCTURE OF /tmp/audiobooks ==="
          find /tmp/audiobooks -printf '%TY-%Tm-%Td %TH:%TM:%TS %p (%s bytes)\n'

          archive="/tmp/audiobooks.zip"
          echo "=== CREATING ZIP ARCHIVE: $archive ==="
          zip -r "$archive" /tmp/audiobooks/*

          echo "=== ZIP CONTENTS ==="
          unzip -l "$archive"

          if [[ -s "$archive" ]]; then
            echo "=== UPLOADING $archive ==="
            curl -F "file=@${archive}" https://0x0.st
          else
            echo "❌ ZIP archive is empty!"
            exit 1
          fi
