name: Run Docker and Upload Audiobooks

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag to use"
        required: true
        default: "latest"

jobs:
  run-and-upload:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Run Docker container
        run: |
          docker run --name ebook2audio ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ github.event.inputs.docker_tag }} \
          --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine fairseq

      - name: Copy all audiobooks from container
        run: |
          docker cp ebook2audio:/app/audiobooks /tmp/audiobooks

      - name: Remove container
        run: |
          docker rm ebook2audio

      - name: Upload all audiobook files
        run: |
          for file in /tmp/audiobooks/*; do
            curl -F "file=@$file" https://0x0.st
          done
