name: Run Docker and Upload Audiobooks

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag to use"
        required: true
        default: "latest"

jobs:
  run-and-upload:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Create output directory
        run: |
          mkdir -p /tmp/audiobooks
          chmod 777 -R /tmp/audiobooks

      - name: Run Docker container with volume mount
        run: |
          docker run --rm \
            -v /tmp/audiobooks:/app/audiobooks \
            ${{ secrets.DOCKER_USERNAME }}/ebook2audiobook:${{ github.event.inputs.docker_tag }} \
            --headless --script_mode full_docker \
            --language eng \
            --ebook "tools/workflow-testing/test1.txt" \
            --tts_engine fairseq

      - name: Verify output files exist
        run: |
          if [ -d /tmp/audiobooks ] && [ "$(ls -A /tmp/audiobooks)" ]; then
            echo "✅ Output files generated successfully:"
            ls -la /tmp/audiobooks
          else
            echo "❌ No output files found in /tmp/audiobooks!"
            exit 1
          fi

      - name: Create ZIP archive and upload
        run: |
          cd /tmp
          echo "=== Creating ZIP archive ==="
          zip -r audiobooks.zip audiobooks
          
          echo "=== ZIP contents ==="
