name: Conditional Test Ubuntu Headless

on:
  push:
    branches:
      - act-trigger
  workflow_dispatch:
    inputs:
      run_english_fairseq_single:
        description: 'Run English Fairseq single test'
        type: boolean
        default: false
      run_english_fairseq_batch:
        description: 'Run English Fairseq batch test'
        type: boolean
        default: false
      run_english_fairseq_custom_voice_single:
        description: 'Run English Fairseq Custom Voice single test'
        type: boolean
        default: false
      run_unusual_fairseq_single:
        description: 'Run Unusual Fairseq single test'
        type: boolean
        default: false
      run_unusual_fairseq_custom_voice_single:
        description: 'Run Unusual Fairseq Custom Voice single test'
        type: boolean
        default: false
      run_english_vits_single:
        description: 'Run English VITS single test'
        type: boolean
        default: false
      run_english_vits_custom_voice_single:
        description: 'Run English VITS Custom Voice single test'
        type: boolean
        default: false
      run_english_yourtts_single:
        description: 'Run English YourTTS single test'
        type: boolean
        default: false
      run_english_yourtts_custom_voice_single:
        description: 'Run English YourTTS Custom Voice single test'
        type: boolean
        default: false
      run_default_single:
        description: 'Run Default single test'
        type: boolean
        default: false
      run_default_xtts_custom_voice_single:
        description: 'Run Default XTTS Custom Voice single test'
        type: boolean
        default: false
      run_all_tests:
        description: 'Run all tests'
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test_matrix: ${{ steps.set-matrix.outputs.test_matrix }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.run_all_tests }}" == "true" ]]; then
            echo "test_matrix=["
            echo '"english_fairseq_single",'
            echo '"english_fairseq_batch",'
            echo '"english_fairseq_custom_voice_single",'
            echo '"unusual_fairseq_single",'
            echo '"unusual_fairseq_custom_voice_single",'
            echo '"english_vits_single",'
            echo '"english_vits_custom_voice_single",'
            echo '"english_yourtts_single",'
            echo '"english_yourtts_custom_voice_single",'
            echo '"default_single",'
            echo '"default_xtts_custom_voice_single"'
            echo "]" | tr -d '\n'
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "test_matrix=[" > matrix.txt
            if [[ "${{ github.event.inputs.run_english_fairseq_single }}" == "true" ]]; then
              echo '"english_fairseq_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_english_fairseq_batch }}" == "true" ]]; then
              echo '"english_fairseq_batch",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_english_fairseq_custom_voice_single }}" == "true" ]]; then
              echo '"english_fairseq_custom_voice_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_unusual_fairseq_single }}" == "true" ]]; then
              echo '"unusual_fairseq_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_unusual_fairseq_custom_voice_single }}" == "true" ]]; then
              echo '"unusual_fairseq_custom_voice_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_english_vits_single }}" == "true" ]]; then
              echo '"english_vits_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_english_vits_custom_voice_single }}" == "true" ]]; then
              echo '"english_vits_custom_voice_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_english_yourtts_single }}" == "true" ]]; then
              echo '"english_yourtts_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_english_yourtts_custom_voice_single }}" == "true" ]]; then
              echo '"english_yourtts_custom_voice_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_default_single }}" == "true" ]]; then
              echo '"default_single",' >> matrix.txt
            fi
            if [[ "${{ github.event.inputs.run_default_xtts_custom_voice_single }}" == "true" ]]; then
              echo '"default_xtts_custom_voice_single",' >> matrix.txt
            fi
            # Remove trailing comma if present
            sed -i '$ s/,$//' matrix.txt
            echo "]" >> matrix.txt
            cat matrix.txt | tr -d '\n'
          else
            # For push events, run all tests
            echo "test_matrix=["
            echo '"english_fairseq_single",'
            echo '"english_fairseq_batch",'
            echo '"english_fairseq_custom_voice_single",'
            echo '"unusual_fairseq_single",'
            echo '"unusual_fairseq_custom_voice_single",'
            echo '"english_vits_single",'
            echo '"english_vits_custom_voice_single",'
            echo '"english_yourtts_single",'
            echo '"english_yourtts_custom_voice_single",'
            echo '"default_single",'
            echo '"default_xtts_custom_voice_single"'
            echo "]" | tr -d '\n'
          fi >> $GITHUB_OUTPUT

  run-tests:
    needs: setup
    if: ${{ fromJson(needs.setup.outputs.test_matrix)[0] != null }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.setup.outputs.test_matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Check Python version
        run: python --version
        
      - name: Install the system packages
        run: |
          sudo apt-get update &&
          sudo apt-get install -y gcc g++ make wget git calibre ffmpeg nodejs espeak espeak-ng rustc cargo libmecab-dev mecab mecab-ipadic-utf8 curl libsndfile1-dev libc-dev sox &&
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash - &&
          sudo apt-get install -y nodejs &&
          sudo apt-get clean &&
          sudo rm -rf /var/lib/apt/lists/*

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install the python requirements
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          pip install -r requirements.txt

      - name: pip Install unict
        run: pip install unidic-lite unidic

      - name: Download the unict dictionary
        run: |
          python -m unidic download
          mkdir -p ~/.local/share/unidic

      - name: Set UniDic environment variable
        run: echo "UNIDIC_DIR=$HOME/.local/share/unidic" >> $GITHUB_ENV

      - name: Help command python app.py
        run: python app.py --help

      - name: Create test files
        run: |
          mkdir -p tools/workflow-testing
          CONTENT=$'"This is a test sentence," she said. "Here'\''s another one."\nThe quick brown fox jumps over the lazy dog, but the cat stays still.\nNumbers like 123,456.78 should also be tested.\nWhat happens if we use question marks? Or exclamation points!\n"Nested quotes are '\''interesting'\''," he noted.'
          echo -e "$CONTENT" > tools/workflow-testing/test1.txt
          echo -e "$CONTENT" > tools/workflow-testing/test2.txt
          echo -e "$CONTENT" > tools/workflow-testing/test3.txt
          echo -e "$CONTENT" > tools/workflow-testing/test4.txt
          echo -e "$CONTENT" > tools/workflow-testing/test5.txt

      # English Fairseq single test
      - name: English Fairseq headless single test
        if: ${{ matrix.test == 'english_fairseq_single' }}
        run: python app.py --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine fairseq

      # English Fairseq batch test
      - name: English Fairseq headless batch test
        if: ${{ matrix.test == 'english_fairseq_batch' }}
        run: python app.py --headless --script_mode full_docker --language eng --ebooks_dir "tools/workflow-testing" --tts_engine fairseq

      # English Fairseq Custom-Voice single test
      - name: English Fairseq Custom-Voice headless single test
        if: ${{ matrix.test == 'english_fairseq_custom_voice_single' }}
        run: python app.py --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine fairseq --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      # Unusual Fairseq single test
      - name: Wipe models/tts folder before unusual fairseq test
        if: ${{ matrix.test == 'unusual_fairseq_single' }}
        run: rm -rf models/tts/*

      - name: Unusual Fairseq headless single test
        if: ${{ matrix.test == 'unusual_fairseq_single' }}
        run: python app.py --headless --script_mode full_docker --language urd-script_devanagari --ebook "tools/workflow-testing/test1.txt" --tts_engine fairseq

      # Unusual Fairseq Custom-Voice single test
      - name: Wipe models/tts folder before unusual fairseq custom voice test
        if: ${{ matrix.test == 'unusual_fairseq_custom_voice_single' }}
        run: rm -rf models/tts/*

      - name: Unusual Fairseq Custom-Voice headless single test
        if: ${{ matrix.test == 'unusual_fairseq_custom_voice_single' }}
        run: python app.py --headless --script_mode full_docker --language urd-script_devanagari --ebook "tools/workflow-testing/test1.txt" --tts_engine fairseq --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      # English Vits single test
      - name: Wipe models/tts folder before vits test
        if: ${{ matrix.test == 'english_vits_single' }}
        run: rm -rf models/tts/*

      - name: English Vits headless single test
        if: ${{ matrix.test == 'english_vits_single' }}
        run: python app.py --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine vits

      # English Vits Custom-Voice single test
      - name: Wipe models/tts folder before vits custom voice test
        if: ${{ matrix.test == 'english_vits_custom_voice_single' }}
        run: rm -rf models/tts/*

      - name: English Vits Custom-Voice headless single test
        if: ${{ matrix.test == 'english_vits_custom_voice_single' }}
        run: python app.py --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine vits --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      # English Yourtts single test
      - name: Wipe models/tts folder before yourtts test
        if: ${{ matrix.test == 'english_yourtts_single' }}
        run: rm -rf models/tts/*

      - name: English Yourtts headless single test
        if: ${{ matrix.test == 'english_yourtts_single' }}
        run: python app.py --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine yourtts

      # English Yourtts Custom-Voice single test
      - name: Wipe models/tts folder before yourtts custom voice test
        if: ${{ matrix.test == 'english_yourtts_custom_voice_single' }}
        run: rm -rf models/tts/*

      - name: English Yourtts Custom-Voice headless single test
        if: ${{ matrix.test == 'english_yourtts_custom_voice_single' }}
        run: python app.py --headless --script_mode full_docker --language eng --ebook "tools/workflow-testing/test1.txt" --tts_engine yourtts --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      # Default single test
      - name: Wipe models/tts folder before default test
        if: ${{ matrix.test == 'default_single' }}
        run: rm -rf models/tts/*

      - name: Default headless single test
        if: ${{ matrix.test == 'default_single' }}
        run: python app.py --headless --script_mode full_docker --ebook "tools/workflow-testing/test1.txt"

      # Default xtts Custom-Voice single test
      - name: Wipe models/tts folder before default xtts custom voice test
        if: ${{ matrix.test == 'default_xtts_custom_voice_single' }}
        run: rm -rf models/tts/*

      - name: Default xtts headless Custom-Voice single test
        if: ${{ matrix.test == 'default_xtts_custom_voice_single' }}
        run: python app.py --headless --script_mode full_docker --ebook "tools/workflow-testing/test1.txt" --tts_engine xtts --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"
